server:
  port: 9092

spring:
  application:
    name: owl-auth
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:3131/owl-auth'
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true